apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
spec:
  selector:
    app: order-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080 # The port this service will be available on inside the cluster
      targetPort: 5100 # The port on the container that the traffic should be forwarded to
